---
services:
  umeboshi:
    container_name: umeboshi
    image: ghcr.io/umeboshi
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # General
      NODE_ENV: "development"
      # Database
      UMEBOSHI_DATABASE_SCHEME: "${DATABASE_SCHEME:-postgresql}"
      UMEBOSHI_DATABASE_USERNAME: "DATABASE_USERNAME"
      UMEBOSHI_DATABASE_PASSWORD: "DATABASE_PASSWORD"
      UMEBOSHI_DATABASE_HOST: "DATABASE_HOST"
      UMEBOSHI_DATABASE_PORT: "${DATABASE_PORT:-5432}"
      UMEBOSHI_DATABASE_NAME: "DATABASE_NAME"
...
