erDiagram

    %%%%%%%%%%%%%
    %% General %%
    %%%%%%%%%%%%%

    %% User
    %% The user of the system
    user ||--|| profile : has
    user ||--o{ user_account : has
    user ||--o| tenant : is
    user {
        uuid id PK
        uuid profile_id FK
        text username
        text password
        text salt
    }

    %% User Account
    user_account {
        uuid user_id PK,FK
        uuid account_id PK,FK
    }

    %% Contact
    contact ||--|| profile : has
    contact {
        uuid id PK
        uuid profile_id FK
        text company
    }

    %% Profile
    profile {
        uuid id PK
        text prefix
        text first_name
        text middle_name
        text last_name
        text suffix
        text phonetic_first_name
        text phonetic_middle_name
        text phonetic_last_lame
        text nickname
    }

    %% Email
    email {
        uuid id PK
        text email
    }

    profile ||--o{ profile_email : has
    email ||--o{ profile_email : is
    profile_email {
        uuid profile_id PK,FK
        uuid email_id PK,FK
    }

    %% Telephone Number
    telephone_number {
        uuid id PK
        text country_code
        text number
    }

    profile ||--o{ profile_telephone_number : has
    telephone_number ||--o{ profile_telephone_number : is
    profile_telephone_number {
        uuid profile_id PK,FK
        uusid telephone_number_id PK,FK
    }

    %% Address
    address }|--|| city : has
    address {
        uuid id PK
        text city_id
        text street
        text premise
        text postal_code
    }

    profile ||--o| profile_address : has
    address ||--o| profile_address : is
    profile_address {
        uuid contact_id PK,FK
        uusid address_id PK,FK
    }

    %% City
    city }|--|| division : has
    city {
        uuid id PK
        uuid division_id FK
        text name
    }

    %% Division
    division }|--|| country : has
    division {
        uuid id PK
        uuid country_id FK
        text name
        text iso_3166_2
    }

    %% Country
    country ||--|{ country_currency : use
    country {
        uuid id PK
        text name
        text official_state_name
        text iso_3166_1
        text iso_3166_1_alpha_2
        text iso_3166_1_alpha_3
    }

    %% Transaction
    transaction ||--o{ journal : contain
    transaction {
        uuid id PK
        uuid transaction_type_id FK
        uuid currency_id FK
        text description
        uuid source_account_id
        uuid destination_account_id
        timestamptz created
        timestamptz completed
        %% money original_cost
        %% money tax
        %% money adjustment
        %% money discount
        %% enum tax_expense
    }

    %% Transaction Type
    transaction_type ||--o{ transaction : categorize
    transaction_type {
        uuid id PK
        text name
    }

    %% Tenant
    tenant {
        uuid id PK
        uuid user_id FK
        uuid property_id FK
    }

    %% Contract
    contract ||--|| property : lease
    contract {
        uuid id PK
        text name
        timestampz activeate_date
        timestampz start_date
        timestampz end_date
        enum status
    }

    %% User Contract
    user ||--o{ user_contract : own
    contract ||--o{ user_contract : execute
    user_contract {
        uuid user_id PK,FK
        uuid contract_id PK,FK
    }

    %% Property
    property ||--|| address : has
    property {
        uuid id PK
        text key PK
        uuid address_id FK
        text parcel_number_local
        text parcel_number_state
        text parcel_number_property_id
        text taxing_district_code
        text taxing_district_description
        smallint section
        smallint township
        smallint range
        text subdivision_name
        smallint subdivision_section
        smallint deeded_acres
        text political_township
        smallint lot_number
        text state_tax_district
        text lot
        text block
    }

    %%%%%%%%%%%%%
    %% Finance %%
    %%%%%%%%%%%%%

    %% Account
    account ||--o{ user_account : is
    account ||--o{ journal : affect
    account {
        uuid id PK
        uuid account_type_id FK
        text name
        uuid type
    }

    account_type ||--o{ account : categorize
    account_type {
        uuid id PK
        text name
        text description
    }

    %% Chart of Account
    %% Asset, Liability, Equity, Revenue, Expense, Other
    chart_of_account ||--|{ chart_of_account : contain
    chart_of_account ||--o{ journal : record
    chart_of_account {
        uuid id PK
        uuid parent_id FK
        uuid chart_of_account_type_id FK
        uuid transaction_id FK
        text name
        text description
        boolean active
    }

    %% Chart of Account Type
    chart_of_account_type ||--o{ chart_of_account : categorize
    chart_of_account_type {
        uuid id PK
        text name
        text description
    }

    %% Journal
    %% Chronological listing of business events using accounting
    %% debit-and-credit language
    %% Ledger
    %% Copy of journal's events, sorted by category or account
    journal {
        uuid id PK
        uuid transaction_id FK "(Index)"
        uuid chart_of_account_id FK "(Index)"
        uuid currency_id FK
        text description
        enum type "(Index), [debit | credit]"
        money amount "(Positive)"
        timestamptz created
    }

    %% Currency
    currency ||--|{ country_currency : has
    currency ||--o{ journal : has
    currency {
        uuid id PK
        text name
        text abbreviation
        text symbol
        char(3) iso_4217
        text fractional_unit
        smallserial base
    }

    country_currency {
        uuid country_id PK,FK
        uuid currency_id PK,FK
    }
